# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pointcloud.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pointcloud.proto',
  package='collector_pkg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10pointcloud.proto\x12\rcollector_pkg\"3\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01i\x18\x04 \x01(\x02\"?\n\nPointCloud\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.collector_pkg.Point\x12\x0b\n\x03seq\x18\x02 \x01(\r\"$\n\x07\x43ostmap\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\r\"o\n\x15PointCloudCostmapPair\x12-\n\npointcloud\x18\x01 \x01(\x0b\x32\x19.collector_pkg.PointCloud\x12\'\n\x07\x63ostmap\x18\x02 \x01(\x0b\x32\x16.collector_pkg.Costmap\"D\n\x0ePairCollection\x12\x32\n\x04pair\x18\x01 \x03(\x0b\x32$.collector_pkg.PointCloudCostmapPairb\x06proto3')
)




_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='collector_pkg.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='collector_pkg.Point.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='collector_pkg.Point.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='collector_pkg.Point.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='collector_pkg.Point.i', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=86,
)


_POINTCLOUD = _descriptor.Descriptor(
  name='PointCloud',
  full_name='collector_pkg.PointCloud',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='collector_pkg.PointCloud.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='collector_pkg.PointCloud.seq', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=151,
)


_COSTMAP = _descriptor.Descriptor(
  name='Costmap',
  full_name='collector_pkg.Costmap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='collector_pkg.Costmap.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='collector_pkg.Costmap.data', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=189,
)


_POINTCLOUDCOSTMAPPAIR = _descriptor.Descriptor(
  name='PointCloudCostmapPair',
  full_name='collector_pkg.PointCloudCostmapPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointcloud', full_name='collector_pkg.PointCloudCostmapPair.pointcloud', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='costmap', full_name='collector_pkg.PointCloudCostmapPair.costmap', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=302,
)


_PAIRCOLLECTION = _descriptor.Descriptor(
  name='PairCollection',
  full_name='collector_pkg.PairCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pair', full_name='collector_pkg.PairCollection.pair', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=372,
)

_POINTCLOUD.fields_by_name['points'].message_type = _POINT
_POINTCLOUDCOSTMAPPAIR.fields_by_name['pointcloud'].message_type = _POINTCLOUD
_POINTCLOUDCOSTMAPPAIR.fields_by_name['costmap'].message_type = _COSTMAP
_PAIRCOLLECTION.fields_by_name['pair'].message_type = _POINTCLOUDCOSTMAPPAIR
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['PointCloud'] = _POINTCLOUD
DESCRIPTOR.message_types_by_name['Costmap'] = _COSTMAP
DESCRIPTOR.message_types_by_name['PointCloudCostmapPair'] = _POINTCLOUDCOSTMAPPAIR
DESCRIPTOR.message_types_by_name['PairCollection'] = _PAIRCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
  DESCRIPTOR = _POINT,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:collector_pkg.Point)
  ))
_sym_db.RegisterMessage(Point)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUD,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:collector_pkg.PointCloud)
  ))
_sym_db.RegisterMessage(PointCloud)

Costmap = _reflection.GeneratedProtocolMessageType('Costmap', (_message.Message,), dict(
  DESCRIPTOR = _COSTMAP,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:collector_pkg.Costmap)
  ))
_sym_db.RegisterMessage(Costmap)

PointCloudCostmapPair = _reflection.GeneratedProtocolMessageType('PointCloudCostmapPair', (_message.Message,), dict(
  DESCRIPTOR = _POINTCLOUDCOSTMAPPAIR,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:collector_pkg.PointCloudCostmapPair)
  ))
_sym_db.RegisterMessage(PointCloudCostmapPair)

PairCollection = _reflection.GeneratedProtocolMessageType('PairCollection', (_message.Message,), dict(
  DESCRIPTOR = _PAIRCOLLECTION,
  __module__ = 'pointcloud_pb2'
  # @@protoc_insertion_point(class_scope:collector_pkg.PairCollection)
  ))
_sym_db.RegisterMessage(PairCollection)


# @@protoc_insertion_point(module_scope)
